#ifndef _MQTT_TOPICS_H_

#define _MQTT_TOPICS_H_

enum mqtt_topic_type {
  SONIC_SENSOR1_DOOR_STATUS,
  TEMP_SENSOR1_TEMPERATURE,
  TEMP_SENSOR2_TEMPERATURE,
  TEMP_SENSOR3_TEMPERATURE,
  TEMP_SENSOR4_TEMPERATURE,
  TEMP_SENSOR5_TEMPERATURE,
  DEVICE_FIRMWARE_OTA_LINK,
  MAX_MQTT_TOPICS,
};

enum mqtt_notification_topic_type {
  NOTIFICATION_DEVICE_STATUS,
  MAX_MQTT_NOTIFICATION_TOPICS,
};

#endif

