#ifndef _MQTT_TOPICS_H_

#define _MQTT_TOPICS_H_

enum mqtt_topic_type {
  TEMP_SENSOR_TRIGER,
  TEMP_SENSOR_INTERVAL,
  TEMP_SENSOR_TEMPERATURE,
  TEMP_SENSOR_PRESSURE,
  TEMP_SENSOR_HUMIDITY,
  TEMP_SENSOR_BATTERY,
  TEMP_SENSOR_BATTERY_HISTORY,
  TEMP_SENSOR_DEBUG_MODE,
  TEMP_SENSOR_DEBUG,
  TEMP_SENSOR_SERVO_POSITION,
  DEVICE_FIRMWARE_OTA_LINK,
  MAX_MQTT_TOPICS,
};

enum mqtt_notification_topic_type {
  NOTIFICATION_DEVICE_STATUS,
  MAX_MQTT_NOTIFICATION_TOPICS,
};

#endif

