#ifndef _MQTT_TOPICS_H_

#define _MQTT_TOPICS_H_

enum mqtt_topic_type {
  SONIC_SENSOR_TRIGER,
  SONIC_SENSOR_INTERVAL,
  SONIC_SENSOR_TIMEOUT,
  SONIC_SENSOR_DENOISE,
  SONIC_SENSOR_DENOISE_DELAY,
  SONIC_SENSOR_ERROR_THRESHOLD,
  SONIC_SENSOR_DOOR_STATUS,
  SONIC_SENSOR_DOOR_OPEN_THRESHOLD,
  SONIC_SENSOR_DOOR_CLOSE_THRESHOLD,
  SONIC_SENSOR_VELOCITY_THRESHOLD,
  SONIC_SENSOR_DEBUG_MODE,
  SONIC_SENSOR_MEASURED_TIME,
  SONIC_SENSOR_MEASURED_DISTANCE,
  SONIC_SENSOR_MEASURED_DISTANCE_HISTORY,
  SONIC_SENSOR_MEASURED_AVERAGE_DISTANCE,
  SONIC_SENSOR_DOOR_OPENER_TRIGGER,
  SONIC_SENSOR_DOOR_OPENER_TRIGGER_TIME,
  SONIC_SENSOR_DOOR_OPENER_TRIGGER_INTERVAL,
  SONIC_SENSOR_DEBUG,
  DEVICE_FIRMWARE_OTA_LINK,
  MAX_MQTT_TOPICS,
};

enum mqtt_notification_topic_type {
  NOTIFICATION_DEVICE_STATUS,
  NOTIFICATION_SONIC_SENSOR_DOOR_STATUS,
  MAX_MQTT_NOTIFICATION_TOPICS,
};

#endif

